"""Aliases revisados entre nomes do feed de partidas e valuations.

As chaves são nomes de times do CSV de partidas; cada lista contém nomes
alternativos que podem aparecer no catálogo de clubes ou em player_valuations.
Todos os valores passam por normalização sem acentos no script principal.
"""

ALIASES_TIME_PARTIDAS = {
    "Ajaccio GFCO": ["GFC Ajaccio", "Gazelec Ajaccio", "Ajaccio GFCO"],
    "Alaves": ["Deportivo Alaves", "Alaves"],
    "Almeria": ["UD Almeria", "Almeria"],
    "Angers": ["Angers SCO"],
    "America MG": [
        "America Mineiro", "America Futebol Clube MG", "America FC MG",
        "America Futebol Clube (MG)",
    ],
    "Arles": ["AC Arles Avignon"],
    "Atalanta": ["Atalanta BC"],
    "Ath Bilbao": ["Athletic Bilbao", "Athletic Club Bilbao"],
    "Ath Madrid": ["Atletico de Madrid", "Atletico Madrid"],
    "Athletico-PR": [
        "Club Athletico Paranaense", "Clube Atletico Paranaense",
        "Athletico Paranaense", "Atletico Paranaense",
    ],
    "Atletico GO": [
        "Atletico Clube Goianiense", "Atletico Goianiense", "AC Goianiense",
    ],
    "Atletico-MG": [
        "Clube Atletico Mineiro", "Atletico Mineiro", "Atletico-MG",
    ],
    "Auxerre": ["AJ Auxerre"],
    "Bari": ["AS Bari", "SSC Bari", "Bari FC"],
    "Betis": ["Real Betis Balompie", "Real Betis"],
    "Benevento": ["Benevento Calcio"],
    "Birmingham": ["Birmingham City", "Birmingham City FC"],
    "Blackburn": ["Blackburn Rovers", "Blackburn Rovers FC"],
    "Blackpool": ["Blackpool FC"],
    "Bolton": ["Bolton Wanderers", "Bolton Wanderers FC"],
    "Bochum": ["VfL Bochum"],
    "Bologna": ["Bologna Football Club 1909"],
    "Brighton": ["Brighton & Hove Albion"],
    "Botafogo RJ": [
        "SAF Botafogo", "S A F Botafogo", "Botafogo FR",
        "Botafogo de Futebol e Regatas",
    ],
    "Bordeaux": ["FC Girondins Bordeaux", "Girondins Bordeaux"],
    "Bragantino": ["Red Bull Bragantino"],
    "Braunschweig": ["Eintracht Braunschweig"],
    "Brest": ["Stade Brestois 29", "Stade Brestois"],
    "Brescia": ["Brescia Calcio"],
    "Caen": ["SM Caen", "Stade Malherbe Caen"],
    "Cagliari": ["Cagliari Calcio"],
    "Cardiff": ["Cardiff City"],
    "Ceara": ["Ceará Sporting Club"],
    "Celta": ["Celta de Vigo"],
    "Clermont": ["Clermont Foot 63"],
    "Como": ["Como 1907"],
    "Corinthians": ["Sport Club Corinthians Paulista"],
    "Coritiba": ["Coritiba Foot Ball Club"],
    "Cremonese": ["US Cremonese"],
    "Darmstadt": ["SV Darmstadt 98"],
    "Dijon": ["Dijon FCO"],
    "Dortmund": ["Borussia Dortmund"],
    "Eibar": ["SD Eibar"],
    "Ein Frankfurt": ["Eintracht Frankfurt"],
    "Espanol": ["RCD Espanyol Barcelona", "RCD Espanyol", "Espanyol Barcelona"],
    "Evian Thonon Gaillard": [
        "FC Evian Thonon Gaillard", "Evian Thonon Gaillard FC",
        "Thonon Evian Grand Geneve FC",
    ],
    "FC Koln": ["1.FC Köln"],
    "Flamengo RJ": ["CR Flamengo", "Clube de Regatas do Flamengo", "Flamengo"],
    "Figueirense": ["Figueirense FC", "Figueirense Futebol Clube"],
    "Fiorentina": ["ACF Fiorentina"],
    "Frosinone": ["Frosinone Calcio"],
    "Genoa": ["Genoa CFC"],
    "Goias": ["Goias EC", "Goias Esporte Clube"],
    "Gremio": ["Grêmio Foot-Ball Porto Alegrense"],
    "Greuther Furth": ["SpVgg Greuther Fürth"],
    "Guingamp": ["EA Guingamp"],
    "Hamburg": ["Hamburger SV", "Hamburg SV"],
    "Hannover": ["Hannover 96"],
    "Hercules": ["Hercules CF", "Hercules de Alicante"],
    "Heidenheim": ["1. Fußballclub Heidenheim 1846"],
    "Hertha": ["Hertha BSC"],
    "Hoffenheim": ["TSG 1899 Hoffenheim"],
    "Huddersfield": ["Huddersfield Town"],
    "Huesca": ["SD Huesca"],
    "Hull": ["Hull City"],
    "Ingolstadt": ["FC Ingolstadt 04"],
    "Inter": ["Inter Milan"],
    "Internacional": ["Sport Club Internacional"],
    "Ipswich": ["Ipswich Town"],
    "Kaiserslautern": ["1 FC Kaiserslautern"],
    "La Coruna": ["Deportivo de La Coruña"],
    "Las Palmas": ["UD Las Palmas"],
    "Leeds": ["Leeds United"],
    "Lecce": ["US Lecce"],
    "Leganes": ["CD Leganés"],
    "Leicester": ["Leicester City"],
    "Lens": ["RC Lens"],
    "Levante": ["Levante UD"],
    "Leverkusen": ["Bayer 04 Leverkusen"],
    "Lille": ["LOSC Lille"],
    "Lazio": ["SS Lazio", "Società Sportiva Lazio S.p.A."],
    "Livorno": ["AS Livorno", "US Livorno 1915"],
    "Luton": ["Luton Town"],
    "Mallorca": ["RCD Mallorca"],
    "Man City": ["Manchester City", "Manchester City FC"],
    "Man United": ["Manchester United", "Manchester United FC"],
    "Marseille": ["Olympique Marseille"],
    "MGladbach": ["Borussia Monchengladbach"],
    "M'gladbach": ["Borussia Monchengladbach"],
    "Mainz": ["1.FSV Mainz 05"],
    "Montpellier": ["Montpellier HSC"],
    "Lyon": ["Olympique Lyon"],
    "Nautico": ["Clube Nautico Capibaribe", "Nautico Capibaribe"],
    "Napoli": ["SSC Napoli"],
    "Newcastle": ["Newcastle United"],
    "Nice": ["OGC Nice"],
    "Nottm Forest": ["Nottingham Forest", "Nottingham Forest FC"],
    "Nott'm Forest": ["Nottingham Forest", "Nottingham Forest FC"],
    "Novara": ["Novara FC", "Novara Calcio"],
    "Nurnberg": ["1 FC Nuremberg", "1 FC Nurnberg"],
    "Norwich": ["Norwich City"],
    "Osasuna": ["CA Osasuna"],
    "Oviedo": ["Real Oviedo"],
    "Paderborn": ["SC Paderborn 07"],
    "Paris SG": ["Paris Saint-Germain", "Paris Saint Germain", "PSG"],
    "Parana": ["Parana Clube"],
    "Parma": ["Parma FC", "Parma Calcio 1913"],
    "Palmeiras": ["Sociedade Esportiva Palmeiras"],
    "Pescara": ["Delfino Pescara 1936"],
    "Pisa": ["Pisa Sporting Club"],
    "Portuguesa": ["Associacao Portuguesa de Desportos", "Portuguesa de Desportos"],
    "Ponte Preta": ["AA Ponte Preta", "Associacao Atletica Ponte Preta"],
    "QPR": ["Queens Park Rangers", "Queens Park Rangers FC"],
    "Reims": ["Stade Reims"],
    "Rennes": ["Stade Rennais FC", "Stade Rennais"],
    "Roma": ["AS Roma", "Associazione Sportiva Roma"],
    "Salernitana": ["US Salernitana 1919"],
    "Sampdoria": ["UC Sampdoria"],
    "Santander": ["Racing Santander", "Racing Club de Santander"],
    "Santa Cruz": ["Santa Cruz FC PE", "Santa Cruz Futebol Clube"],
    "Sassuolo": ["US Sassuolo"],
    "Sochaux": ["FC Sochaux-Montbéliard"],
    "Sociedad": ["Real Sociedad"],
    "Sp Gijon": ["Sporting Gijon"],
    "Spezia": ["Spezia Calcio"],
    "St Etienne": ["AS Saint-Etienne", "Saint-Etienne"],
    "Stoke": ["Stoke City"],
    "Strasbourg": ["RC Strasbourg Alsace"],
    "Stuttgart": ["VfB Stuttgart"],
    "Swansea": ["Swansea City"],
    "Tottenham": ["Tottenham Hotspur"],
    "Troyes": ["ESTAC Troyes"],
    "Udinese": ["Udinese Calcio"],
    "Union Berlin": ["1.FC Union Berlin"],
    "Verona": ["Hellas Verona", "Hellas Verona FC"],
    "Valladolid": ["Real Valladolid CF"],
    "Vallecano": ["Rayo Vallecano"],
    "Vasco": ["Club de Regatas Vasco da Gama"],
    "West Brom": ["West Bromwich Albion", "West Bromwich Albion FC"],
    "West Ham": ["West Ham United"],
    "Wigan": ["Wigan Athletic"],
    "Wolfsburg": ["VfL Wolfsburg"],
    "Wolves": ["Wolverhampton Wanderers", "Wolverhampton Wanderers FC"],
    "Zaragoza": ["Real Zaragoza"],
}
